adjust scripts logic

diff --git a/jobs/diracx-cms-init-keystore.yaml b/jobs/diracx-cms-init-keystore.yaml
--- a/jobs/diracx-cms-init-keystore.yaml
+++ b/jobs/diracx-cms-init-keystore.yaml
@@ -12,15 +12,41 @@ data:
   init-keystore: |
     #!/usr/bin/env bash
     set -euo pipefail
-    python -m diracx.db init-keystore
+
+    source /activate.sh
+
+    mkdir -p /keystore
+    KEYSTORE_PATH=/keystore/jwks.json
+
+    if [[ -f $KEYSTORE_PATH ]]; then
+        echo "JWKS already exists, this is not supported!"
+        exit 1
+    fi
+
+    python -m diracx.logic rotate-jwk --jwks-path $KEYSTORE_PATH
     
   # The second script: uploads them as a K8s secret
   load-keystore-as-secret: |
     #!/usr/bin/env bash
     set -euo pipefail
-    # This assumes the secret-generation image has logic 
-    # to create a secret from the files in /keystore
-    diracx-generate-secret from-keystore /keystore
+
+    source /activate.sh
+
+    KEYSTORE_PATH=/keystore/jwks.json
+
+    if [[ ! -f $KEYSTORE_PATH ]]; then
+      echo "Keystore is missing"
+      exit 1;
+    fi
+
+    # Check if the keystore secret already exists
+    if kubectl get secret diracx-jwks >/dev/null 2>&1; then
+      echo "diracx-jwks already present, skipping keystore generation"
+      exit 0
+    fi
+
+    # Create the keystore secret
+    kubectl create secret generic diracx-jwks --from-file=$KEYSTORE_PATH
 
 ---
 apiVersion: batch/v1
